/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blue_testso_MyJNI */

#ifndef _Included_com_blue_testso_MyJNI
#define _Included_com_blue_testso_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blue_testso_MyJNI
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_blue_testso_MyJNI_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_blue_testso_MyJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_blue_testso_MyJNI_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
